package org.vaadin.artur.testgenerator.demo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class VisualDemo extends CustomComponent {

    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private Table table_1;
    @AutoGenerated
    private NativeSelect nativeSelect_1;
    @AutoGenerated
    private NativeButton nativeButton_1;
    @AutoGenerated
    private Accordion accordion_1;
    @AutoGenerated
    private MenuBar menuBar_1;
    @AutoGenerated
    private ListSelect listSelect_1;
    @AutoGenerated
    private Label label_1;
    @AutoGenerated
    private InlineDateField inlineDateField_1;
    @AutoGenerated
    private CheckBox checkBox_1;
    @AutoGenerated
    private ComboBox comboBox_1;
    @AutoGenerated
    private Link link_2;
    @AutoGenerated
    private Link link_1;
    @AutoGenerated
    private Panel panel_3;
    @AutoGenerated
    private VerticalLayout verticalLayout_2;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;
    @AutoGenerated
    private Button cancelButton;
    @AutoGenerated
    private Button okButton;
    @AutoGenerated
    private PasswordField passwordField_1;
    @AutoGenerated
    private TextField textField_2;

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public VisualDemo() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
        MenuItem menu1 = menuBar_1.addItem("Menu 1", null);
        menu1.addItem("Sub menu 1", null);
        menuBar_1.addItem("Menu 2", null);
    }

    public NativeSelect getNativeSelect_1() {
        return nativeSelect_1;
    }

    public ListSelect getListSelect_1() {
        return listSelect_1;
    }

    public ComboBox getComboBox_1() {
        return comboBox_1;
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");

        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");

        // panel_3
        panel_3 = buildPanel_3();
        mainLayout.addComponent(panel_3, "top:51.0px;left:60.0px;");

        // link_1
        link_1 = new Link();
        link_1.setCaption("Forgot Password?");
        link_1.setImmediate(false);
        link_1.setWidth("-1px");
        link_1.setHeight("-1px");
        mainLayout.addComponent(link_1, "top:20.0px;left:263.0px;");

        // link_2
        link_2 = new Link();
        link_2.setCaption("Privacy Policy");
        link_2.setImmediate(false);
        link_2.setWidth("-1px");
        link_2.setHeight("-1px");
        mainLayout.addComponent(link_2, "top:266.0px;left:37.0px;");

        // comboBox_1
        comboBox_1 = new ComboBox();
        comboBox_1.setImmediate(false);
        comboBox_1.setWidth("-1px");
        comboBox_1.setHeight("-1px");
        mainLayout.addComponent(comboBox_1, "top:171.0px;left:340.0px;");

        // accordion_1
        accordion_1 = buildAccordion_1();
        mainLayout.addComponent(accordion_1, "top:102.0px;left:540.0px;");

        // nativeButton_1
        nativeButton_1 = new NativeButton();
        nativeButton_1.setCaption("NativeButton");
        nativeButton_1.setImmediate(true);
        nativeButton_1.setWidth("-1px");
        nativeButton_1.setHeight("-1px");
        mainLayout.addComponent(nativeButton_1, "top:378.0px;left:181.0px;");

        // nativeSelect_1
        nativeSelect_1 = new NativeSelect();
        nativeSelect_1.setImmediate(false);
        nativeSelect_1.setWidth("-1px");
        nativeSelect_1.setHeight("-1px");
        mainLayout.addComponent(nativeSelect_1, "top:378.0px;left:400.0px;");

        // table_1
        table_1 = new Table();
        table_1.setImmediate(false);
        table_1.setWidth("565px");
        table_1.setHeight("-1px");
        mainLayout.addComponent(table_1, "top:420.0px;left:115.0px;");

        return mainLayout;
    }

    @AutoGenerated
    private Panel buildPanel_3() {
        // common part: create layout
        panel_3 = new Panel();
        panel_3.setCaption("Login Details");
        panel_3.setImmediate(false);
        panel_3.setWidth("-1px");
        panel_3.setHeight("-1px");

        // verticalLayout_2
        verticalLayout_2 = buildVerticalLayout_2();
        panel_3.setContent(verticalLayout_2);

        return panel_3;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_2() {
        // common part: create layout
        verticalLayout_2 = new VerticalLayout();
        verticalLayout_2.setImmediate(false);
        verticalLayout_2.setWidth("-1px");
        verticalLayout_2.setHeight("-1px");
        verticalLayout_2.setMargin(true);
        verticalLayout_2.setSpacing(true);

        // textField_2
        textField_2 = new TextField();
        textField_2.setCaption("Login");
        textField_2.setImmediate(false);
        textField_2.setWidth("-1px");
        textField_2.setHeight("24px");
        verticalLayout_2.addComponent(textField_2);

        // passwordField_1
        passwordField_1 = new PasswordField();
        passwordField_1.setCaption("Password");
        passwordField_1.setImmediate(false);
        passwordField_1.setWidth("-1px");
        passwordField_1.setHeight("-1px");
        verticalLayout_2.addComponent(passwordField_1);

        // horizontalLayout_1
        horizontalLayout_1 = buildHorizontalLayout_1();
        verticalLayout_2.addComponent(horizontalLayout_1);

        return verticalLayout_2;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1() {
        // common part: create layout
        horizontalLayout_1 = new HorizontalLayout();
        horizontalLayout_1.setImmediate(false);
        horizontalLayout_1.setWidth("100.0%");
        horizontalLayout_1.setHeight("-1px");
        horizontalLayout_1.setMargin(false);

        // okButton
        okButton = new Button();
        okButton.setCaption("OK");
        okButton.setImmediate(true);
        okButton.setWidth("-1px");
        okButton.setHeight("-1px");
        horizontalLayout_1.addComponent(okButton);

        // cancelButton
        cancelButton = new Button();
        cancelButton.setCaption("Cancel");
        cancelButton.setImmediate(true);
        cancelButton.setWidth("-1px");
        cancelButton.setHeight("-1px");
        horizontalLayout_1.addComponent(cancelButton);
        horizontalLayout_1.setComponentAlignment(cancelButton,
                new Alignment(34));

        return horizontalLayout_1;
    }

    @AutoGenerated
    private Accordion buildAccordion_1() {
        // common part: create layout
        accordion_1 = new Accordion();
        accordion_1.setImmediate(true);
        accordion_1.setWidth("260px");
        accordion_1.setHeight("258px");

        // checkBox_1
        checkBox_1 = new CheckBox();
        checkBox_1.setCaption("CheckBox");
        checkBox_1.setImmediate(false);
        checkBox_1.setWidth("-1px");
        checkBox_1.setHeight("-1px");
        accordion_1.addTab(checkBox_1, "Tab", null);

        // inlineDateField_1
        inlineDateField_1 = new InlineDateField();
        inlineDateField_1.setImmediate(false);
        inlineDateField_1.setWidth("-1px");
        inlineDateField_1.setHeight("-1px");
        accordion_1.addTab(inlineDateField_1, "DateField tab", null);

        // label_1
        label_1 = new Label();
        label_1.setImmediate(false);
        label_1.setWidth("-1px");
        label_1.setHeight("-1px");
        label_1.setValue("Label");
        accordion_1.addTab(label_1, "Tab 3", null);

        // listSelect_1
        listSelect_1 = new ListSelect();
        listSelect_1.setImmediate(false);
        listSelect_1.setDescription("select");
        listSelect_1.setWidth("-1px");
        listSelect_1.setHeight("-1px");
        accordion_1.addTab(listSelect_1, "select tab", null);

        // menuBar_1
        menuBar_1 = new MenuBar();
        menuBar_1.setImmediate(false);
        menuBar_1.setWidth("-1px");
        menuBar_1.setHeight("-1px");
        accordion_1.addTab(menuBar_1, "menu", null);

        return accordion_1;
    }

    public Table getTable() {
        return table_1;
    }

}
